CREATE TABLE announcements
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name             TEXT UNIQUE NOT NULL,
    user_id          INTEGER     NOT NULL,
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_announcements_id PRIMARY KEY (id)
);

CREATE TABLE pets
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name             TEXT UNIQUE NOT NULL,
    user_id          INTEGER     NOT NULL,
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_pets_id PRIMARY KEY (id)
);